---
title: "MATH 216 Participation Points Totals"
date: Last updated on `r format(Sys.time(), '%d %B, %Y')`
output: html_document
---

Your goal is to get at least **40 participation points** for the semester to earn full credit for the participation component of the course. Earning more than 40 points is awesome, but will not have any additional impact on your grade. 

```{r setup, include=FALSE}
library(gsheet)
library(tidyverse)
library(randomcoloR)
library(kableExtra)

data <- gsheet2tbl('HIDDEN')

totals <- data %>% 
  group_by(Name) %>% 
  summarize(total = sum(Points, na.rm=T)) 

set.seed(1)
totals$key <- distinctColorPalette(26)
set.seed(1)
totals$key2 <- sample(letters)

total_sort<- totals %>% 
  select(total, key2) %>% 
  arrange(-total) 

n=0
for(i in 1:length(total_sort$total)){
  if(total_sort$total[i]>=40){total_sort$total[i] = "> 40"; n=n+1}
}
```


```{r echo=F}
kable(total_sort) %>% 
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F) %>% 
  row_spec(1:n, bold = T,  background = "#D0F0C0")
```

```{r include=FALSE}
for(i in totals$Name){

test <- data %>% 
  filter(Name == i) %>% 
  select(Timestamp, Points, Why)

key <- totals %>% 
  filter(Name == i) 

key$key<-sub(".", "", key$key)
  write.csv(test, paste(key$key,"csv", sep="."))
}
```



